name: shas

on: [push, pull_request]
env:
  VERSION: $(git rev-parse --short=8 ${{ github.sha }}

jobs:
  format:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: shas
      run: |
        echo "large: ${{github.sha}}"
        echo "short: $VERSION"
        mkdir -p test
