name: shas

on: [push, pull_request]

jobs:
  format:
    runs-on: ${{ matrix.os }}
    env:
      VERSION: "$(git rev-parse --short ${{ github.sha }})"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: shas
      run: |
        echo "large: ${{github.sha}}"
        echo $VERSION
        mkdir -p test
        ls -la test
